version: "3"

networks:
  elevator-network:

services:
  elevator-system-postgres:
    build: postgres/.
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - elevator-network
    restart: always